<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Green Kart - Check Functionalities</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>90</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>bb972e5d-2d41-4428-84fc-c048442798b1</testSuiteGuid>
   <testCaseLink>
      <guid>67f4eb5b-855e-4c73-a746-4458c02b42d3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/RS-Academy/GreenKart/Check Quantity with Loop increment</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9474bbf1-7562-405c-9bc3-7a344e64ff33</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fbd6081b-e088-4883-a4ea-0b9124cb07c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75c045e0-401a-43eb-a445-cb4ee506741d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb5a0cd1-739a-424b-a7ab-9ed814179331</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f58b9186-9dea-4683-8565-c54fa294994a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a23c4d7e-ab72-4720-99a9-3775b0c0b252</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8e683bf-6a5f-4ed4-be1e-ea65b97def5a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>24a7c695-d714-4303-96e4-53bfbb5fce99</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/RS-Academy/GreenKart/CheckItemPriceMultiple - Datafile</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f08aeff2-4a6d-40ae-9e4d-184f38b62a15</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/GreenKart/ItemPrice</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>f08aeff2-4a6d-40ae-9e4d-184f38b62a15</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>item</value>
         <variableId>671d28fd-82cf-47b0-8aaf-7b4d04a90c2d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f08aeff2-4a6d-40ae-9e4d-184f38b62a15</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>price</value>
         <variableId>2090a300-73c6-47ed-8662-bd45c405f97f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f782fac-2d4a-47e1-97c0-eaab2039b634</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7fea2b1b-74e7-4df8-b951-e5da0c2a82f1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/RS-Academy/GreenKart/AddItemToCartWithIncreasedQuantity - Datafile</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f8126270-19ac-43c2-8460-987077096e9e</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/GreenKart/ItemQuantity</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>f8126270-19ac-43c2-8460-987077096e9e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>item</value>
         <variableId>2b6cce89-aec6-4b4c-a4eb-512d1ebea912</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f8126270-19ac-43c2-8460-987077096e9e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>quantity</value>
         <variableId>ec38aa7c-cedd-4c76-9f5d-0d263204dcee</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>09860cb4-2107-45c9-bddd-b3475f1e950f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/RS-Academy/GreenKart/Update quantity without incrementor</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>1cf22576-ca04-428f-b2a2-8b0fa78acce8</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/GreenKart/ItemQuantity</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>1cf22576-ca04-428f-b2a2-8b0fa78acce8</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>item</value>
         <variableId>e6376abc-a3d9-4581-8e7d-7c51d20e3cc9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1cf22576-ca04-428f-b2a2-8b0fa78acce8</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>quantity</value>
         <variableId>05363f50-facc-44c8-9eed-1e80bdd68727</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3d91b387-ff21-4c3e-bc79-d08b5a214393</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/RS-Academy/GreenKart/Search and add item</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>15924360-a0c5-42f4-b232-952e088bcdfb</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/GreenKart/ItemPriceQuanity</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>15924360-a0c5-42f4-b232-952e088bcdfb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>item</value>
         <variableId>a6201788-aca6-4a71-bce0-c64e587adbd5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>15924360-a0c5-42f4-b232-952e088bcdfb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>price</value>
         <variableId>108536c1-33fc-4bcf-b0b1-e43bb93944c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>15924360-a0c5-42f4-b232-952e088bcdfb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>quantity</value>
         <variableId>cf8771e1-2d72-4d33-a315-f354eb07a98a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0fdd6c11-4a02-4e01-8c34-4fc5e4d326e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44f79433-673d-4142-b5ec-d60347376408</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
