<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Green Kart - Check Functionalities</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>90</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>bb972e5d-2d41-4428-84fc-c048442798b1</testSuiteGuid>
   <testCaseLink>
      <guid>67f4eb5b-855e-4c73-a746-4458c02b42d3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/RS-Academy/GreenKart/Check Quantity with Loop increment</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9474bbf1-7562-405c-9bc3-7a344e64ff33</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fbd6081b-e088-4883-a4ea-0b9124cb07c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75c045e0-401a-43eb-a445-cb4ee506741d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb5a0cd1-739a-424b-a7ab-9ed814179331</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f58b9186-9dea-4683-8565-c54fa294994a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a23c4d7e-ab72-4720-99a9-3775b0c0b252</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8e683bf-6a5f-4ed4-be1e-ea65b97def5a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>24a7c695-d714-4303-96e4-53bfbb5fce99</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/RS-Academy/GreenKart/CheckItemPriceMultiple - Datafile</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f08aeff2-4a6d-40ae-9e4d-184f38b62a15</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/GreenKart/ItemPrice</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>f08aeff2-4a6d-40ae-9e4d-184f38b62a15</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>item</value>
         <variableId>671d28fd-82cf-47b0-8aaf-7b4d04a90c2d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f08aeff2-4a6d-40ae-9e4d-184f38b62a15</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>price</value>
         <variableId>2090a300-73c6-47ed-8662-bd45c405f97f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7fea2b1b-74e7-4df8-b951-e5da0c2a82f1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/RS-Academy/GreenKart/AddItemToCartWithIncreasedQuantity - Datafile</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f8126270-19ac-43c2-8460-987077096e9e</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/GreenKart/ItemQuantity</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>f8126270-19ac-43c2-8460-987077096e9e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>item</value>
         <variableId>2b6cce89-aec6-4b4c-a4eb-512d1ebea912</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f8126270-19ac-43c2-8460-987077096e9e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>quantity</value>
         <variableId>ec38aa7c-cedd-4c76-9f5d-0d263204dcee</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
