<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cartPrice</name>
   <tag></tag>
   <elementGuidId>437f4849-1800-4035-a60a-a3931e78496b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='cart-info']/table/tbody/tr[2]/td/strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>ed86a66f-2a01-4071-b792-2a067ad63941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1727318065242</value>
      <webElementGuid>03c8c8da-fcf8-4af8-9548-a4ab45773423</webElementGuid>
   </webElementProperties>
</WebElementEntity>
