<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Product</name>
   <tag></tag>
   <elementGuidId>2a75cdbf-6ed9-4be4-8c98-b072ce425b92</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[(contains(text(), '${itemName}') or contains(., '${itemName}')) and @class = 'product']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h4[@class='product-name'][contains(text(),'${itemName}')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${itemName}</value>
      <webElementGuid>25cecc7a-2ed2-4698-889f-e261b0cfb64b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>33429226-31b4-49f6-9d52-d42704402397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product</value>
      <webElementGuid>6c94382a-e7cb-4e74-888b-5e391482f4bb</webElementGuid>
   </webElementProperties>
</WebElementEntity>
