<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Amazon</name>
   <tag></tag>
   <elementGuidId>596d4818-23ef-422b-892a-61fb2d8b6924</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.jumbotron > div > a:nth-child(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='main-content']/div/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Amazon&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0006a02d-d1f4-4152-a1bd-f44d711a6c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-lg btn-success</value>
      <webElementGuid>f7ca9ca3-afed-493a-a6ce-531cf4d7c01f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.amazon.com/gp/product/0956733298/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&amp;tag=compendiumdev-20&amp;camp=1789&amp;creative=9325&amp;linkCode=as2&amp;creativeASIN=0956733298&amp;linkId=ae4fe6a1132097050fc6c2cbe2ae717f</value>
      <webElementGuid>3f54af6d-a949-4f23-a4e0-8b53f7e2429a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>c3db188b-0546-49ac-8ac3-9960fbba2f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener noreferrer</value>
      <webElementGuid>e617e320-719c-4b10-b828-72b9a8be1588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Amazon</value>
      <webElementGuid>7f65c762-074d-453c-bb6a-53bdd260bdb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;jumbotron&quot;]/div[1]/a[@class=&quot;btn btn-lg btn-success&quot;]</value>
      <webElementGuid>945c62a0-91ec-4f55-9681-5921e051a496</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main-content']/div/div/a[2]</value>
      <webElementGuid>0e1bf276-ab36-4a11-bcdf-a68ace943e47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Amazon')]</value>
      <webElementGuid>b5e87c76-2458-4d6b-a94f-c5f848325f03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy the ebook'])[1]/following::a[1]</value>
      <webElementGuid>36c6ebc9-52e1-42fa-94df-a1bd8d6a0024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tracks Automating and Testing Case Study'])[1]/following::a[2]</value>
      <webElementGuid>ec641b4d-a362-4964-a895-73f455c917ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[Read a .pdf Sample]'])[1]/preceding::a[1]</value>
      <webElementGuid>385f3f15-ec9c-447d-9996-2b6a34a08354</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[Read sample online]'])[1]/preceding::a[2]</value>
      <webElementGuid>c83304c1-0c70-4482-9d90-649cafba341f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Amazon']/parent::*</value>
      <webElementGuid>5f09c404-6097-4ea2-af4d-3118f4129b84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.amazon.com/gp/product/0956733298/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&amp;tag=compendiumdev-20&amp;camp=1789&amp;creative=9325&amp;linkCode=as2&amp;creativeASIN=0956733298&amp;linkId=ae4fe6a1132097050fc6c2cbe2ae717f')]</value>
      <webElementGuid>1e605e09-903e-48f0-b611-e4a19c48c21b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>34c90e34-e3eb-4aea-b992-4b106db23ba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.amazon.com/gp/product/0956733298/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&amp;tag=compendiumdev-20&amp;camp=1789&amp;creative=9325&amp;linkCode=as2&amp;creativeASIN=0956733298&amp;linkId=ae4fe6a1132097050fc6c2cbe2ae717f' and (text() = 'Amazon' or . = 'Amazon')]</value>
      <webElementGuid>3de01463-617b-485f-aafa-6a45f127bf7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
