<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_About the book</name>
   <tag></tag>
   <elementGuidId>510c14da-9256-4dc3-a7a7-a1336e1deb6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#about-the-book</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='about-the-book']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;About the book&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>8c926dd9-d151-4a06-a75e-ee50eea9e0d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>about-the-book</value>
      <webElementGuid>efc71834-7a1d-47f6-9ca1-4cd7bd032304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>About the book</value>
      <webElementGuid>dd530e42-6465-4b3e-adf8-9ac90307428b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;about-the-book&quot;)</value>
      <webElementGuid>99a9f523-488d-47f1-bdd8-50706537eb97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='about-the-book']</value>
      <webElementGuid>462b60a6-6e13-4f33-9efc-b87f8014411e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main-content']/h2</value>
      <webElementGuid>346a5cb2-947e-4619-b021-91350f7ed337</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[Book Support Page]'])[1]/following::h2[1]</value>
      <webElementGuid>8f5b580a-85d6-4314-9ad8-084d31cf7b34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[Read sample online]'])[1]/following::h2[1]</value>
      <webElementGuid>3816a218-3914-44ea-9636-a420d96d42d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='read the REST API documentation,'])[1]/preceding::h2[1]</value>
      <webElementGuid>4537082c-86c1-43af-9709-a5cde4dba815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='how to tell if the application is using the API,'])[1]/preceding::h2[1]</value>
      <webElementGuid>e7bd37b5-6f51-408f-b3e2-3921277ce33a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='About the book']/parent::*</value>
      <webElementGuid>52470823-cb5c-46c0-ac22-19a31b71c4af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/h2</value>
      <webElementGuid>a5a45c71-d86f-4a0a-ba30-dddabbedf12e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'about-the-book' and (text() = 'About the book' or . = 'About the book')]</value>
      <webElementGuid>2ffe188a-e453-453e-9a96-658fd6725c3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
