<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Resources</name>
   <tag></tag>
   <elementGuidId>87efe9b2-07ee-42d1-8c82-6946d3add4f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#resources</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='resources']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Resources&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>f9c0df1c-0c45-43da-a35d-f60fe75e7795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>resources</value>
      <webElementGuid>6d117b0e-7522-40e7-884c-8f05a0062894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Resources</value>
      <webElementGuid>9425cb16-1abe-4f4c-8951-a4e962e24a6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resources&quot;)</value>
      <webElementGuid>3dbcdf13-43f4-476b-a793-d148da143a13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='resources']</value>
      <webElementGuid>7722b0bf-8a61-49a9-80ba-2a32faaa2ea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main-content']/h2[2]</value>
      <webElementGuid>4d12a5bb-241e-42fb-9a4d-ab110271795e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='build abstraction code to make your automated efforts readable and maintainable'])[1]/following::h2[1]</value>
      <webElementGuid>1855ccb6-432e-476a-95f5-36eedf9ada7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='automate the API with Java using REST-assured,'])[1]/following::h2[1]</value>
      <webElementGuid>83469c60-bbf3-4d4f-9254-95811b88997a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='support page'])[1]/preceding::h2[1]</value>
      <webElementGuid>7f778b10-bebc-4a46-bfb7-421c73a7bf0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The source code'])[1]/preceding::h2[1]</value>
      <webElementGuid>81ea1ce3-727a-4c21-97cf-158c78ffb1b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2[2]</value>
      <webElementGuid>4abb050f-1641-4beb-bf4d-9990561a6ffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'resources' and (text() = 'Resources' or . = 'Resources')]</value>
      <webElementGuid>51921a35-0fac-4214-add1-a7a6730e9b46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
