<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Book</name>
   <tag></tag>
   <elementGuidId>8884f638-7655-4120-8c67-5ac945715a3b</elementGuidId>
   <imagePath>Screenshots/Targets/Page_Automating and Testing A REST API Case Study Book by Alan Richardson - EvilTester.com/img_Tracks Automating and Testing Case Study_image-center.png</imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='main-content']/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.image-center</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_Automating and Testing A REST API Case Study Book by Alan Richardson - EvilTester.com/img_Tracks Automating and Testing Case Study_image-center.png</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#main-content >> internal:role=img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b31aa5ee-75a5-42f2-b7ad-1d4a15965883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image-center</value>
      <webElementGuid>97abb49b-0f8f-4714-9210-3c1093e5d869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/dominion_images/books/tracksApiTesting_cover_200x260.png</value>
      <webElementGuid>e77bdced-f140-4cd4-9d87-27862da709e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;jumbotron&quot;]/img[@class=&quot;image-center&quot;]</value>
      <webElementGuid>364e4f9c-cbf5-4ea1-9ddc-5c653f837744</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main-content']/div/img</value>
      <webElementGuid>06dff214-e394-4e48-b753-c747e288da62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>3c5d1ee4-6fc0-416c-9220-16f9e527b294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/dominion_images/books/tracksApiTesting_cover_200x260.png']</value>
      <webElementGuid>75289401-2841-4e3c-8e46-18472ff4049c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
