<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Description</name>
   <tag></tag>
   <elementGuidId>fa5ae4d6-f06e-4e2f-8238-cbbe5bc1e5ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>section#main-content > p:nth-child(1)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='main-content']/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;A Case study of Testing and Automating a REST API.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>35fe8061-563c-4375-bfc6-e194c18ee27e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>A Case study of Testing and Automating a REST API.</value>
      <webElementGuid>82d9d9fd-34db-48cb-b3d4-1cf7f1f5cc7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/p[1]</value>
      <webElementGuid>55d87e88-def3-421f-a09a-781efb7fb923</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main-content']/p</value>
      <webElementGuid>237d6e53-47c7-441e-a8f8-eafc4f20482e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tracks Automating and Testing Case Study'])[1]/following::p[1]</value>
      <webElementGuid>c7a058f1-392b-47c0-8373-9ecbebd442f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Form'])[1]/following::p[1]</value>
      <webElementGuid>5b273c2e-8abc-4796-aa79-8e96c2f635da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy the ebook'])[1]/preceding::p[5]</value>
      <webElementGuid>5fd505ba-102f-403e-bb05-9337e73f95bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amazon'])[1]/preceding::p[5]</value>
      <webElementGuid>b315eefb-2e05-49d9-bb5a-7ac75ef077a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='A Case study of Testing and Automating a REST API.']/parent::*</value>
      <webElementGuid>cc13e0bc-4643-4f0b-8fae-443e5f741d9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>b3ed3b99-94db-4a95-afd6-f947091cb728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'A Case study of Testing and Automating a REST API.' or . = 'A Case study of Testing and Automating a REST API.')]</value>
      <webElementGuid>c5f790e8-6a6c-4d46-9315-ab57575eaffa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
