<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Selection</name>
   <tag></tag>
   <elementGuidId>5d02971c-c161-4235-b4a3-4332c1ca159a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//Select[@id='combo_facility']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
