<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_JavaScript</name>
   <tag></tag>
   <elementGuidId>4a3f4a34-a4b9-40b9-a3dc-37e176bb9dad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.rootdropdownmenuitem:nth-child(4) > ul:nth-child(2) > li:nth-child(3) > a:nth-child(1)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cssmenu']/ul/li[4]/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;JavaScript&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>88600bc6-7dcb-4083-9ab4-6db17130c01c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/page/onlinetraining/courses/#protect-the-square</value>
      <webElementGuid>a1fe3350-ca55-431d-b02d-b67488011545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JavaScript</value>
      <webElementGuid>ea510d5c-44ad-4510-b83d-fa62ee34938e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cssmenu&quot;)/ul[1]/li[@class=&quot;rootdropdownmenuitem&quot;]/ul[@class=&quot;dropdownmenu&quot;]/li[@class=&quot;dropdownmenuitem&quot;]/a[1]</value>
      <webElementGuid>a51635b7-b7a0-4322-aa82-de2b1928849b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cssmenu']/ul/li[4]/ul/li[3]/a</value>
      <webElementGuid>51f3cfe8-b5f8-49f1-ac78-9bf0f6bdb36b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'JavaScript')]</value>
      <webElementGuid>7acb83da-025f-4e61-bcc7-a4f30ba65cee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Technical Web Testing'])[1]/following::a[1]</value>
      <webElementGuid>53b5b9ee-f94e-43ff-9361-d39e06ced386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Evil Tester Talks'])[1]/following::a[2]</value>
      <webElementGuid>36a5be59-826a-4bd0-bd8b-25a6e2a6d282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='... All Courses'])[1]/preceding::a[1]</value>
      <webElementGuid>0674e70c-7d9c-4b35-a4eb-bcde13677ead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resources'])[1]/preceding::a[2]</value>
      <webElementGuid>255ff3e9-536e-4b08-9568-84ff2b703c42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='JavaScript']/parent::*</value>
      <webElementGuid>aa6b4748-52f2-4d50-b0a9-9b3e30b6e122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/page/onlinetraining/courses/#protect-the-square')]</value>
      <webElementGuid>ce2f34f6-d228-454e-9409-0cb4438b0fc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li[3]/a</value>
      <webElementGuid>18e8f8d8-3643-449f-9667-29645ef6fb0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/page/onlinetraining/courses/#protect-the-square' and (text() = 'JavaScript' or . = 'JavaScript')]</value>
      <webElementGuid>8946289f-719a-4901-a053-fe72d460f050</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
