<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Talks</name>
   <tag></tag>
   <elementGuidId>acafb0f8-1b6f-4c66-98b2-2d8f1a7e7d68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.rootdropdownmenuitem:nth-child(6) > a:nth-child(1)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cssmenu']/ul/li[6]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Talks&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d2b45327-e9fb-4e53-989f-40656361461f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/conference/</value>
      <webElementGuid>f04716b7-5da3-4fbc-b97e-4850eff750da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Talks</value>
      <webElementGuid>bb5853e5-5567-4e12-a503-805d25d34fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cssmenu&quot;)/ul[1]/li[@class=&quot;rootdropdownmenuitem&quot;]/a[1]</value>
      <webElementGuid>95395323-f1da-4fa2-9280-529c3c83c4d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cssmenu']/ul/li[6]/a</value>
      <webElementGuid>79f3196e-8903-4052-9032-cdb111a6b454</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Talks')])[2]</value>
      <webElementGuid>4e38b2f2-7b67-4e03-abdb-b9111a3e3f5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Patreon Mentoring'])[1]/following::a[1]</value>
      <webElementGuid>111953ac-e820-4c3b-8c38-fad095ef0788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recommended Books List'])[1]/following::a[2]</value>
      <webElementGuid>a96e985c-17b0-4b57-a040-e94028b78b51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tools'])[1]/preceding::a[1]</value>
      <webElementGuid>64badafe-68a4-4dcc-87e9-01223b9221f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Podcast'])[1]/preceding::a[2]</value>
      <webElementGuid>428366d2-a198-4f34-9dd5-6a423f7dc960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Talks']/parent::*</value>
      <webElementGuid>961d4dec-46d9-4e75-a852-7130809fa5f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/conference/')]</value>
      <webElementGuid>7ff8e8b0-e59b-4f32-90c6-5d18c0b109ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>a0c14393-0834-4a77-bd51-0b4dbfa73ff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/conference/' and (text() = 'Talks' or . = 'Talks')]</value>
      <webElementGuid>9e86581e-6a04-4f72-af57-2b05c9ea6209</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
