<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Training</name>
   <tag></tag>
   <elementGuidId>ee41ca5a-fc2c-4540-bc17-6663b7875139</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.rootdropdownmenuitem:nth-child(4) > a:nth-child(1)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cssmenu']/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Training&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4882de7c-4039-4476-a1a5-8dd1c0703995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/page/onlinetraining/courses/</value>
      <webElementGuid>e64aa6c0-96bd-4658-a411-8d2f035c22af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Training</value>
      <webElementGuid>9a9c5131-996d-414e-a57b-d01d5d34b08f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cssmenu&quot;)/ul[1]/li[@class=&quot;rootdropdownmenuitem&quot;]/a[1]</value>
      <webElementGuid>53bdb147-4b56-4e7e-afd6-b2f8bec3ce8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cssmenu']/ul/li[4]/a</value>
      <webElementGuid>023f92d3-7fe2-4593-bd11-f17af71fb400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Training')]</value>
      <webElementGuid>d3e2fc6a-cd60-493f-bfa8-7fdb13e7f51f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='... All Books'])[1]/following::a[1]</value>
      <webElementGuid>3b407f43-e153-46f3-bbd6-1b3314cf2e23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automating API'])[1]/following::a[2]</value>
      <webElementGuid>19241c4f-c20e-40c7-bfff-8a7a6cfcf82a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Evil Tester Talks'])[1]/preceding::a[1]</value>
      <webElementGuid>8aed5b57-6b42-4b6d-b815-dc25673a46c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Technical Web Testing'])[1]/preceding::a[2]</value>
      <webElementGuid>f4721ba4-abf2-41f8-9b5b-d603cccc94ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Training']/parent::*</value>
      <webElementGuid>900b57e9-acc5-4157-885b-6786db9caff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/page/onlinetraining/courses/')]</value>
      <webElementGuid>ecf14d6e-aab4-4f59-9e20-0e48733c11f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[4]/a</value>
      <webElementGuid>ff6ac36b-826a-4cba-91dd-1f1c5576ccd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/page/onlinetraining/courses/' and (text() = 'Training' or . = 'Training')]</value>
      <webElementGuid>163c0c3a-c80a-4ff9-af5c-5bf89bd9c860</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
