<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Mailing List</name>
   <tag></tag>
   <elementGuidId>08f99d41-8bfd-4c10-98c6-294269058256</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.top-unit > h2:nth-child(1)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='main']/div[10]/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Mailing List&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>8f7c30bb-6555-4280-9687-fa5a3943a4da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center</value>
      <webElementGuid>8c1f65d1-3af6-4396-81b3-fdee123289f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mailing List</value>
      <webElementGuid>41f46333-7906-4347-9d9b-4c86ed35a9d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;top-unit&quot;]/h2[@class=&quot;text-center&quot;]</value>
      <webElementGuid>1fe06ae1-164c-409b-b196-5fd1b6d7faf0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main']/div[10]/h2</value>
      <webElementGuid>e5cf2c3e-c07d-4b64-b253-d4e521cb2256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Podcast Episodes &amp; Show Notes'])[1]/following::h2[1]</value>
      <webElementGuid>ba65d78b-67f7-4edc-973d-d65fbe909127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Podcast - The Evil Tester Show'])[1]/following::h2[1]</value>
      <webElementGuid>546272fa-b748-47d5-b872-f695cf78b021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subscribe to our mailing list'])[1]/preceding::h2[1]</value>
      <webElementGuid>4966eb47-3245-423e-bdec-9bd99ae2dcb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email List Privacy Policy'])[1]/preceding::h2[1]</value>
      <webElementGuid>5bddcc07-94ee-43cb-963c-1ef6645908dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mailing List']/parent::*</value>
      <webElementGuid>404c34cb-a526-4d8f-b548-8afe32c23a81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/h2</value>
      <webElementGuid>6c4a6e59-ff39-4d3a-8f64-071c8c17ce96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Mailing List' or . = 'Mailing List')]</value>
      <webElementGuid>54af3e2a-96b8-4ee7-9762-6b230457ff6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
