<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Podcast - The Evil Tester Show</name>
   <tag></tag>
   <elementGuidId>d377992a-27f8-410d-971d-3c708a24db42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.jumbotron:nth-child(12) > h2:nth-child(1)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='main']/div[9]/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Podcast - The Evil Tester Show&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>6e6e00de-64e5-4b58-9568-6bbda91fb51a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center</value>
      <webElementGuid>be811373-eeef-447b-a8a4-582b5a6afb73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Podcast - The Evil Tester Show</value>
      <webElementGuid>da6f138e-8554-4a2e-a165-f2a640541a26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;jumbotron&quot;]/h2[@class=&quot;text-center&quot;]</value>
      <webElementGuid>35e29849-4936-4ba0-a5c3-18da3c48777d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main']/div[9]/h2</value>
      <webElementGuid>757744dd-f3c3-472f-8ffe-2a6e32893986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more about the books'])[1]/following::h2[1]</value>
      <webElementGuid>345611bf-7aa1-41bb-a077-2c6b55034830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Java For Testers'])[2]/following::h2[1]</value>
      <webElementGuid>e0964357-c397-46c6-aed6-603a33a711ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Podcast Episodes &amp; Show Notes'])[1]/preceding::h2[1]</value>
      <webElementGuid>1badcd36-e63e-403d-b70d-bbc6e607411c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mailing List'])[1]/preceding::h2[1]</value>
      <webElementGuid>c4c7f0ca-19b2-4d9e-8b2c-2efd4d3e6e91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Podcast - The Evil Tester Show']/parent::*</value>
      <webElementGuid>ef64d687-a7ce-4441-b7ec-53a4d734b6f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/h2</value>
      <webElementGuid>406ad40d-cee8-4631-9387-4c1fd2b28d8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Podcast - The Evil Tester Show' or . = 'Podcast - The Evil Tester Show')]</value>
      <webElementGuid>8ffcb8be-2cf4-43e8-aeb1-df3a6a85361c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
