<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Recent Blog Posts</name>
   <tag></tag>
   <elementGuidId>9b1ce0a3-84bb-4333-b2c3-994f5f31901c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#main > div:nth-child(2) > h2:nth-child(1)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='main']/div[2]/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Recent Blog Posts&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>3cfd18a5-333f-4489-8f7a-ee8b595467ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center</value>
      <webElementGuid>f7a7d463-377b-4ad8-8a90-f19c9683ca77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Recent Blog Posts</value>
      <webElementGuid>268f315b-766a-499a-98b4-1ca0eba3d9ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[2]/h2[@class=&quot;text-center&quot;]</value>
      <webElementGuid>cc4a90dc-ea8e-4361-a06c-c91aa258f9c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main']/div[2]/h2</value>
      <webElementGuid>66dd777a-cf04-4dcd-a1ee-bfb0be296559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Form'])[1]/following::h2[1]</value>
      <webElementGuid>bfcbb4ac-9d0c-475c-a674-32bb55002c9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email List'])[1]/following::h2[1]</value>
      <webElementGuid>ce55aa05-b95e-4afe-bcaf-d29875ffecba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Modelling Software Testing for Naming and Understanding'])[1]/preceding::h2[1]</value>
      <webElementGuid>e451c4f1-34c2-4365-bf1c-8521f4a9352e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kubernetes kubectl cheat sheet notes'])[1]/preceding::h2[1]</value>
      <webElementGuid>89dcb95a-910e-434e-88cd-f2e39912355b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Recent Blog Posts']/parent::*</value>
      <webElementGuid>f507eb33-0a9c-4224-aaa8-70229947f8e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>287fd46b-e603-45ec-b921-5d543c3079b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Recent Blog Posts' or . = 'Recent Blog Posts')]</value>
      <webElementGuid>0dbb5f02-7f00-44b3-ad8e-7a846f73aa79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
