<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_- Back_inventory_details_img</name>
   <tag></tag>
   <elementGuidId>cb0ce141-27bd-4922-935c-0abab466560f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.inventory_details_img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='inventory_item_container']/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a5351b73-b12c-4fbd-af94-b1ea16f63199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inventory_details_img</value>
      <webElementGuid>241c506d-9927-43c7-8e49-f2bb4b5cf99b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>./img/red-tatt-1200x1500.jpg</value>
      <webElementGuid>578b167e-4a5b-47d3-915f-e357fae2f35b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inventory_item_container&quot;)/div[@class=&quot;inventory_details&quot;]/div[@class=&quot;inventory_details_container&quot;]/img[@class=&quot;inventory_details_img&quot;]</value>
      <webElementGuid>1c357e9e-b6f0-4f76-a9a3-90787245b5fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='inventory_item_container']/div/div/img</value>
      <webElementGuid>0a0cd5cd-44d3-49a5-8356-f0890ed31a9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>739df05c-f7c0-4bb5-ba4c-abfc80b78d67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = './img/red-tatt-1200x1500.jpg']</value>
      <webElementGuid>c990a8a2-d4e8-4ee2-86e9-4fa428acaaca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = './img/red-onesie-1200x1500.jpg']</value>
      <webElementGuid>71f421b7-04aa-4082-b81f-ed4fb53b7637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = './img/sauce-pullover-1200x1500.jpg']</value>
      <webElementGuid>78bae1b1-4e48-4be6-9995-4b966f8a6344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = './img/bolt-shirt-1200x1500.jpg']</value>
      <webElementGuid>41b067e6-d085-4dfc-bbcf-061a96acc159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = './img/bike-light-1200x1500.jpg']</value>
      <webElementGuid>da52cc39-de97-4083-8b0c-1a9fab47a6c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
