<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Buy The Paperback_title</name>
   <tag></tag>
   <elementGuidId>4aa8b928-6bc3-4e53-8bae-3fcb58a1d18c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='jumbotron']/div[2]/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>//div[@class='jumbotron']/div[2]/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Buy The Paperback&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fcdc61e7-3392-4c87-8b75-427d61cc9e4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-lg btn-primary</value>
      <webElementGuid>9ce84e81-d9df-4081-a623-2bbb105a00a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://www.amazon.com/exec/obidos/ASIN/0956733271</value>
      <webElementGuid>1c9d0d7e-1de8-4a25-acb6-a4be2c736849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>f3c1d5c0-2813-438a-b4d2-051a746f012c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener noreferrer</value>
      <webElementGuid>e82ab12f-fc66-4cb5-9d5c-f8958c3404b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Buy The Paperback</value>
      <webElementGuid>7ec32e56-fb5e-45a5-91ca-092a3ec50820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;jumbotron&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4&quot;]/a[@class=&quot;btn btn-lg btn-primary&quot;]</value>
      <webElementGuid>17184bed-4833-4fc1-837d-4b6c89ea93b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main-content']/div/div[2]/div[2]/a</value>
      <webElementGuid>2bf6b52f-8dca-4423-aaeb-f0fd135faf21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Buy The Paperback')]</value>
      <webElementGuid>56148184-5f46-4eff-ac06-8c2ce6b7aabe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy The eBook'])[1]/following::a[1]</value>
      <webElementGuid>051ab17c-bf4f-4549-bfe4-4730a3ded9bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='help you laugh not languish.'])[1]/following::a[2]</value>
      <webElementGuid>a6afa52d-9842-4902-8f7e-71a2a8bd4830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download a PDF Sample'])[1]/preceding::a[1]</value>
      <webElementGuid>7d202054-453b-47b8-aa5f-b917180847eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='“something completely different,'])[1]/preceding::a[2]</value>
      <webElementGuid>209e980c-ccf2-4471-a7ba-8c00a58a60ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Buy The Paperback']/parent::*</value>
      <webElementGuid>e0718b09-ee9a-4f51-a250-40966b0afc92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://www.amazon.com/exec/obidos/ASIN/0956733271']</value>
      <webElementGuid>0420c71f-a36c-4b86-b4c2-87ded215460d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>e762a3c0-accc-4fe3-9d0e-2c031b022123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://www.amazon.com/exec/obidos/ASIN/0956733271' and (text() = 'Buy The Paperback' or . = 'Buy The Paperback')]</value>
      <webElementGuid>3d5dd286-fdef-4f60-805d-f1786c34db24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
