<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>imgBook</name>
   <tag></tag>
   <elementGuidId>004e4cc5-3157-431f-87db-3f76f6d8acf6</elementGuidId>
   <imagePath>Screenshots/Targets/Page_Dear Evil Tester - A Software Testing Book - EvilTester.com/imgBook.png</imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='main-content']/div/div/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_Dear Evil Tester - A Software Testing Book - EvilTester.com/imgBook.png</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.col-md-4 > a >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7501b39e-1249-4522-a2ad-c2f5e200ad65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/dominion_images/books/dearEvilTester/dearEvilTesterEbookCover_219x310.png</value>
      <webElementGuid>6ae158d1-c03c-4a29-9f59-8c638cdb2066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;jumbotron&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4&quot;]/a[1]/img[1]</value>
      <webElementGuid>c16e2a6c-4284-4d22-acf0-d73eab26c35a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main-content']/div/div/div/a/img</value>
      <webElementGuid>7216be04-edf2-412a-9656-97473d9d9b66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>bb8d4999-6910-48c5-b601-c5baba34f44e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/dominion_images/books/dearEvilTester/dearEvilTesterEbookCover_219x310.png']</value>
      <webElementGuid>ed948e88-58a9-4e77-ac94-641f76ee88b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
