<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Case Study  Java Desktop Application Technical Testing</name>
   <tag></tag>
   <elementGuidId>095db2ab-7cfd-4ccb-b748-823670bf096e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#case-study--java-desktop-application-technical-testing</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='case-study--java-desktop-application-technical-testing']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Case Study : Java Desktop Application Technical Testing&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>d5808994-df06-4644-9bce-bf61fd4d3461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>case-study--java-desktop-application-technical-testing</value>
      <webElementGuid>7985ec6e-6f71-47e6-b54d-49153a06c7f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Case Study : Java Desktop Application Technical Testing</value>
      <webElementGuid>cbac3750-9aed-41a8-b869-154c5fc9a6a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;case-study--java-desktop-application-technical-testing&quot;)</value>
      <webElementGuid>de4a7964-ba60-42f7-8a71-1e5c074e8bd4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='case-study--java-desktop-application-technical-testing']</value>
      <webElementGuid>44b97b85-5f52-4cf8-954f-01da5830dcf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main-content']/div[2]/h2[12]</value>
      <webElementGuid>673b9d29-a36a-4927-9504-61a061e5d029</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn Exploratory Testing'])[1]/following::h2[1]</value>
      <webElementGuid>f8909b1d-d76b-422e-9ae6-d850414e5a57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How I Test - Web App'])[2]/following::h2[1]</value>
      <webElementGuid>96dc5c74-727f-437d-b537-d950c5279eb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn about this Free Course'])[1]/preceding::h2[1]</value>
      <webElementGuid>2043daaf-37b6-41b0-b498-9d05a7825904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Join The Evil Tester Patreon Community'])[1]/preceding::h2[1]</value>
      <webElementGuid>103567ea-b908-4a37-9f36-7989c2b27483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2[12]</value>
      <webElementGuid>2dd458d7-cb82-4fb0-9ba2-ad16a0c47fbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'case-study--java-desktop-application-technical-testing' and (text() = 'Case Study : Java Desktop Application Technical Testing' or . = 'Case Study : Java Desktop Application Technical Testing')]</value>
      <webElementGuid>1e26719a-f050-4a85-8008-cc102b5a43cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
