<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Test Ability Audit</name>
   <tag></tag>
   <elementGuidId>cb518a7b-b41b-4775-9aa2-28a2d1654fc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#test-ability-audit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='test-ability-audit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Test Ability Audit&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>4627cdb3-168b-4384-a7aa-f576fd9e4867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>test-ability-audit</value>
      <webElementGuid>29484b9c-e25f-409a-8149-ae713d889cc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test Ability Audit</value>
      <webElementGuid>c2b1e994-bb5e-4c17-a236-fc02db898069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;test-ability-audit&quot;)</value>
      <webElementGuid>bacb1123-8c86-42a0-99e4-d04379a18bed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='test-ability-audit']</value>
      <webElementGuid>5e38692a-fd2e-4a7f-bf9d-3040bb9d3298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main-content']/div[2]/h2[8]</value>
      <webElementGuid>7ee454c4-3f72-4100-92f2-5f2b17b9ca9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn about the course'])[1]/following::h2[1]</value>
      <webElementGuid>619279a6-c47b-4be8-92ec-db78436b20b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get Your Message Out'])[2]/following::h2[1]</value>
      <webElementGuid>ad172841-564d-4e26-9cc4-d78dea0081e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn how to audit your Test Ability'])[1]/preceding::h2[1]</value>
      <webElementGuid>9ee7910c-34b4-4a76-8336-27ec3f85ebce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Protect The Square'])[2]/preceding::h2[1]</value>
      <webElementGuid>62d464b8-0876-4db2-80e2-74f51409a09d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2[8]</value>
      <webElementGuid>108965fb-32b6-4cb3-9d58-59dd90148ad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'test-ability-audit' and (text() = 'Test Ability Audit' or . = 'Test Ability Audit')]</value>
      <webElementGuid>44f20f09-ec47-487a-82d2-738b8c9e0ee4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
