<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Image Container</name>
   <tag></tag>
   <elementGuidId>97c10591-4529-413b-a229-4d2d091e90d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.course-cover-list > p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='main-content']/div/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#main-content div >> internal:has-text=&quot;This page contains details of the online courses created and presented by Alan R&quot;i >> div >> internal:role=paragraph</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>d40880b8-dadd-4c7c-805f-76762677ee54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;jumbotron&quot;]/div[@class=&quot;course-cover-list&quot;]/p[1]</value>
      <webElementGuid>6fe644e7-f1e3-42ca-847e-8dfe6914038b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main-content']/div/div/p</value>
      <webElementGuid>03e47a3b-5ae7-4332-b93c-b9f42e72436c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online Courses'])[1]/following::p[2]</value>
      <webElementGuid>6fb3d74c-bf38-4c66-a28a-63591c1700fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Form'])[1]/following::p[2]</value>
      <webElementGuid>82ed786d-a722-4436-bf67-84417a34a116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selenium WebDriver with Java'])[1]/preceding::p[2]</value>
      <webElementGuid>1fbafaab-07f9-4a50-9bd9-aaa34e8727dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selenium WebDriver Support Classes with Java'])[1]/preceding::p[2]</value>
      <webElementGuid>6941cff0-873c-4e6d-b09e-25987fef9e77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/p</value>
      <webElementGuid>7bed7639-0816-4189-8770-1efd69b308cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
