<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Book</name>
   <tag></tag>
   <elementGuidId>2ce01236-4f09-4408-8f24-180d40d0858a</elementGuidId>
   <imagePath>Screenshots/Targets/Page_Java For Testers Book by Alan Richardson - EvilTester.com/img_Book.png</imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='main-content']/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.col-md-4 > img:nth-child(1)</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_Java For Testers Book by Alan Richardson - EvilTester.com/img_Book.png</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#main-content >> internal:role=img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1b1bb810-ab50-4df0-b794-4240ad8d5dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/dominion_images/books/javafortesters/20150904_physical_createspace_trans_231x332.png</value>
      <webElementGuid>d39aa63a-99da-4103-8597-c800c03f682e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;jumbotron&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4&quot;]/img[1]</value>
      <webElementGuid>f9588e18-bcad-417f-9448-245909ee6d33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main-content']/div/div/div/img</value>
      <webElementGuid>38b5b8a9-2b34-46be-b7a3-922fad8185a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>c4f69a14-44a7-49eb-8e87-21dde6b0772e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/dominion_images/books/javafortesters/20150904_physical_createspace_trans_231x332.png']</value>
      <webElementGuid>4841b72a-3dc6-4e33-893f-9f2194f174fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
