<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_itemPrice</name>
   <tag></tag>
   <elementGuidId>a31f97a1-1f66-42c7-a118-ad3e52c37144</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='productCartTables']/tbody/tr/td[5]/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(${itemCount}) > td:nth-of-type(4) > p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;48&quot;i >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>e3fca13d-9931-473d-8aa4-03d0feb1932f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>amount</value>
      <webElementGuid>028cb668-a542-433d-aed6-99f6192c40a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>48</value>
      <webElementGuid>62e2c603-e1e2-4f67-8a52-bab98297bf14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productCartTables&quot;)/tbody[1]/tr[1]/td[5]/p[@class=&quot;amount&quot;]</value>
      <webElementGuid>f6345b8d-12b6-4678-bb0d-3a516b4b3854</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='productCartTables']/tbody/tr/td[5]/p</value>
      <webElementGuid>1f9bfd58-587e-4dcc-951e-ec823f8be762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/following::p[4]</value>
      <webElementGuid>7af90e27-bb23-48a5-8359-af1bbffda895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price'])[1]/following::p[4]</value>
      <webElementGuid>b98289a8-6a80-4b8f-a66e-6fb85c8857f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[1]/preceding::p[1]</value>
      <webElementGuid>b032f56f-d2fc-4667-94e4-3b778866deed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/p</value>
      <webElementGuid>e45e671d-0c02-4ec8-82fb-abfac564507b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '48' or . = '48')]</value>
      <webElementGuid>c9122779-d575-455e-972a-128fdf488caa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
