<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Dear Evil Tester</name>
   <tag></tag>
   <elementGuidId>1f2f06b5-93fe-4c4d-960d-ac6591d9c5fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.jumbotron > ul:nth-child(3) > li:nth-child(2) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='main-content']/div/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Dear Evil Tester&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d80503ed-b5a5-4092-81ad-54bd158ec448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#dear-evil-tester</value>
      <webElementGuid>9f24bca3-7c6a-47ac-a2e4-3ee889b2bf56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dear Evil Tester</value>
      <webElementGuid>6325ed55-cadd-4084-b557-7f4d97219027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;jumbotron&quot;]/ul[1]/li[2]/a[1]</value>
      <webElementGuid>cfa83d91-6590-4cdc-a803-a66c64f2a499</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main-content']/div/ul/li[2]/a</value>
      <webElementGuid>d259bad7-156d-42d9-b344-38c447b38563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Dear Evil Tester')])[2]</value>
      <webElementGuid>2ed90b5d-5640-4b99-9858-69d61e9d4f75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Java For Testers'])[2]/following::a[1]</value>
      <webElementGuid>634b20cb-6b89-4159-95ca-a62baefa2c78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Books Written By Alan Richardson'])[1]/following::a[9]</value>
      <webElementGuid>7cd023d7-c649-4670-8616-08a4a3cdbb45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automating and Testing a REST API'])[1]/preceding::a[1]</value>
      <webElementGuid>5ed74f3b-f1e3-4ed2-a9cf-edd4b9e2c18a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selenium Simplified'])[1]/preceding::a[2]</value>
      <webElementGuid>f1082d31-48e9-4715-9505-07c7e88fd914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#dear-evil-tester')])[2]</value>
      <webElementGuid>2fabf0a1-2c38-4264-82a2-abc1712e012e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/ul/li[2]/a</value>
      <webElementGuid>31a0f335-d195-4868-8172-76af52722ce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#dear-evil-tester' and (text() = 'Dear Evil Tester' or . = 'Dear Evil Tester')]</value>
      <webElementGuid>1e82360f-8857-4e4c-8665-c83b58edbdd7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
