<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Download as a free pdf_interactive cobol</name>
   <tag></tag>
   <elementGuidId>a14428b6-2384-45f1-a5d7-e2fe0bc5a6fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#an-interactive-cobol-interpreter-and-jsp-debugger + p + p + p + p + p + p > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>3e7b317b-f4ed-4948-8091-2c432357b02d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1727058370359</value>
      <webElementGuid>5fa739a6-5737-4762-a140-92d8114dd9a0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
