<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Books Written By Alan Richardson</name>
   <tag></tag>
   <elementGuidId>f52a03df-5382-4dc7-977b-4cf83fb87f4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Books Written By Alan Richardson&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>7fca17ba-6dff-41c4-a066-fae9a015e8a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>e2fc566d-d288-41a8-8759-f208dd1a6080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center</value>
      <webElementGuid>7718c342-92d9-4ce1-8500-dd22e55e932d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Books Written By Alan Richardson</value>
      <webElementGuid>b750fe4f-a258-43b3-b41c-1d6ff3f70cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;title&quot;)</value>
      <webElementGuid>3bf4bb25-f960-4bcc-ae4f-00f302c79e05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='title']</value>
      <webElementGuid>a71d1545-8fb1-456d-894b-83bd551341c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='content']/div/article/h1</value>
      <webElementGuid>c4d97c3b-76a5-4db2-9a60-d5d7226100b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Form'])[1]/following::h1[1]</value>
      <webElementGuid>39ac7f5a-de79-4f29-81aa-3c478b1ac602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email List'])[1]/following::h1[1]</value>
      <webElementGuid>7a845ad5-da35-43aa-80b0-5518b0106c12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Java For Testers'])[2]/preceding::h1[1]</value>
      <webElementGuid>8a47defd-61a5-487e-baf6-7385c21267bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dear Evil Tester'])[2]/preceding::h1[1]</value>
      <webElementGuid>a1335063-22d8-4e7e-a161-b59d87230d0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Books Written By Alan Richardson']/parent::*</value>
      <webElementGuid>aa8853e2-47ed-4f39-823d-cd5546740c20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>8e32a14e-f84b-40b2-a324-6d8145ba3371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'title' and (text() = 'Books Written By Alan Richardson' or . = 'Books Written By Alan Richardson')]</value>
      <webElementGuid>20a69375-d291-4458-810b-dc908b8b4e30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
