<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Automating and Testing a REST API</name>
   <tag></tag>
   <elementGuidId>b52521d8-b2b5-43eb-9af1-f81da692b20c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#automating-and-testing-a-rest-api</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='automating-and-testing-a-rest-api']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Automating and Testing a REST API&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>5e687731-ba25-4e21-8d26-5093bc82fe52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>automating-and-testing-a-rest-api</value>
      <webElementGuid>7cb0868a-5b39-4451-bf19-0f42ed33baf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Automating and Testing a REST API</value>
      <webElementGuid>f23cf007-c172-402d-9321-6385e6fde9f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;automating-and-testing-a-rest-api&quot;)</value>
      <webElementGuid>c28ad2ea-ccbb-4375-b5dd-1e3e721fb16d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='automating-and-testing-a-rest-api']</value>
      <webElementGuid>0756d1e2-d3dc-4251-8af2-2ea011353cba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main-content']/div[2]/h2[3]</value>
      <webElementGuid>6986edba-9323-46a5-97c5-32b7eebbbba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dear Evil Tester'])[3]/following::h2[1]</value>
      <webElementGuid>869d976d-c98c-48fa-9be7-23ef131a5648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selenium Simplified'])[2]/preceding::h2[1]</value>
      <webElementGuid>8ebb33ea-c128-49ae-9e54-9d7681759727</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2[3]</value>
      <webElementGuid>25cddf78-1c55-434b-b75f-3895fb660f68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'automating-and-testing-a-rest-api' and (text() = 'Automating and Testing a REST API' or . = 'Automating and Testing a REST API')]</value>
      <webElementGuid>d9c287de-1816-4fbd-979b-e6a23a06c823</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
