<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Dear Evil Tester</name>
   <tag></tag>
   <elementGuidId>12858469-47de-4a19-bd90-ca8a04e2719d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dear-evil-tester</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='dear-evil-tester']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Dear Evil Tester&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>f6c1d680-93bf-44ed-bc67-8a694966061f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dear-evil-tester</value>
      <webElementGuid>6bce4dee-fd88-48c4-92c4-184f1b5a43f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dear Evil Tester</value>
      <webElementGuid>94a12652-2ae8-4fa0-99ee-10378e9d8855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dear-evil-tester&quot;)</value>
      <webElementGuid>4fe522a3-2af2-4879-85e4-68267ed7e3bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='dear-evil-tester']</value>
      <webElementGuid>bc4da2d1-3927-4ac8-8c3b-5f85665e8221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main-content']/div[2]/h2[2]</value>
      <webElementGuid>63cd2e6f-43f4-4f1d-ac19-9b1c4f4dbb85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Java For Testers'])[3]/following::h2[1]</value>
      <webElementGuid>7045d8aa-62a0-429f-b5cb-4a7b2232e060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automating and Testing a REST API'])[2]/preceding::h2[1]</value>
      <webElementGuid>aac56753-3a77-45a4-aa47-dcf8f06e28f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2[2]</value>
      <webElementGuid>e9201816-74ed-4c39-b702-1c5f51bf8e53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'dear-evil-tester' and (text() = 'Dear Evil Tester' or . = 'Dear Evil Tester')]</value>
      <webElementGuid>f8cbc70d-1cc1-47b6-9767-528acf2ddbb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
