<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_selenium-simplified</name>
   <tag></tag>
   <elementGuidId>d4d6f88a-c8c1-4abc-997a-79f0023a78e6</elementGuidId>
   <imagePath>Screenshots/Targets/Page_Software Testing Books Written By Alan Richardson - EvilTester.com/img_selenium-simplified.png</imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selenium-simplified + p > a > img</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_Software Testing Books Written By Alan Richardson - EvilTester.com/img_selenium-simplified.png</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='main-content']/div[2]/p[15]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>p:nth-child(20) > a</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>70955e0e-16ae-447a-a94e-15d0978e96b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/dominion_images/books/seleniumsimplified2ndsmall.gif</value>
      <webElementGuid>1336a40a-51b3-4f81-8df2-d9569adbc74b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;book-image-center&quot;]/p[15]/a[1]/img[1]</value>
      <webElementGuid>6e7b732e-6350-4c18-942a-210c4f653eed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main-content']/div[2]/p[15]/a/img</value>
      <webElementGuid>588cff9a-a44e-43fa-8aa8-e6e61890966a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[15]/a/img</value>
      <webElementGuid>6f6f0a0a-e85f-42e3-b348-adbc80eee204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/dominion_images/books/seleniumsimplified2ndsmall.gif']</value>
      <webElementGuid>1301f5a1-5ada-42b3-b663-9cc511377f6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
