<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_dear-evil-tester</name>
   <tag></tag>
   <elementGuidId>d50c7cdf-6c4e-413c-97f7-b466af883540</elementGuidId>
   <imagePath>Screenshots/Targets/Page_Software Testing Books Written By Alan Richardson - EvilTester.com/img_dear-evil-tester.png</imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dear-evil-tester + p > a > img</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_Software Testing Books Written By Alan Richardson - EvilTester.com/img_dear-evil-tester.png</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='main-content']/div[2]/p[6]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>p:nth-child(8) > a >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9cd5350d-b1d1-4f9e-bda0-83daf18f199f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/dominion_images/books/dearEvilTester/dearEvilTesterEbookCover_106x150.png</value>
      <webElementGuid>013ce52e-c833-4cc7-a73f-870892e1ae6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;book-image-center&quot;]/p[6]/a[1]/img[1]</value>
      <webElementGuid>772543ba-0e23-451c-b498-5f62d358b5cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main-content']/div[2]/p[6]/a/img</value>
      <webElementGuid>b46afe67-208e-471c-95d8-bf62bf09f751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[6]/a/img</value>
      <webElementGuid>1c11ee35-1fb8-423a-9b9f-b68c34529c0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/dominion_images/books/dearEvilTester/dearEvilTesterEbookCover_106x150.png']</value>
      <webElementGuid>9e79e12c-1c2a-4f6e-9692-9fe12af0da88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
